repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML==6.0.12.12
          - sqlalchemy-stubs==0.4
          - types-aiofiles==23.2.0.0
          - types-redis==4.6.0.20240106

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
        exclude: ^(tests/|docs/|setup.py)

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--check]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["tests/"]

      - id: coverage-check
        name: coverage-check
        entry: coverage run -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["tests/"]

      - id: complexity-check
        name: complexity-check
        entry: xenon
        language: system
        pass_filenames: false
        always_run: true
        args: ["--max-absolute B", "--max-modules B", "--max-average A", "src"]

      - id: security-check
        name: security-check
        entry: safety
        language: system
        pass_filenames: false
        always_run: true
        args: ["check"] 