version: '3.8'

services:
  app:
    platform: linux/arm64/v8
    build: .
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/meme_gen
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./meme_storage:/app/meme_storage
    depends_on:
      - db
      - redis

  db:
    platform: linux/arm64/v8
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meme_gen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    platform: linux/arm64/v8
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    platform: linux/arm64/v8
    image: redislabs/redisinsight:latest
    ports:
      - "8082:8001"
    depends_on:
      - redis

  pgadmin:
    platform: linux/arm64/v8
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data: 