"""Setup configuration for the DSPy Meme Generator package."""

from setuptools import setup, find_packages

setup(
    name="dspy_meme_gen",
    version="0.1.0",
    description="A sophisticated meme generation pipeline using DSPy",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "dspy",
        "fastapi",
        "sqlalchemy",
        "aioredis",
        "prometheus-client",
        "aiohttp",
        "pyyaml",
    ],
    extras_require={
        "dev": [
            "pytest",
            "pytest-cov",
            "pytest-asyncio",
            "pytest-benchmark",
            "mypy",
            "ruff",
            "radon",
            "xenon",
            "safety",
            "bandit",
            "pydocstyle",
            "pylint",
        ],
        "test": [
            "pytest==8.0.0",
            "pytest-asyncio==0.23.5",
            "pytest-cov==4.1.0",
            "pytest-mock==3.12.0",
            "pytest-xdist==3.5.0",
            "pytest-sugar==1.0.0",
            "pytest-timeout==2.2.0",
            "pytest-randomly==3.15.0",
            "pytest-clarity==1.0.1",
            "pytest-env==1.1.3",
            "pytest-html==4.1.1",
            "pytest-metadata==3.1.0",
            "pytest-reportlog==0.3.0",
            "pytest-rerunfailures==13.0",
            "pytest-repeat==0.9.3",
            "pytest-benchmark==4.0.0",
            "pytest-profiling==1.7.0",
            "pytest-picked==0.5.0",
            "pytest-ordering==0.6",
            "pytest-lazy-fixture==0.6.3",
            "pytest-instafail==0.5.0",
            "pytest-freezegun==0.4.2",
            "pytest-faker==3.0.0",
            "pytest-factoryboy==2.6.0",
            "pytest-aiohttp==1.0.5",
            "pytest-aiofiles==1.0.1",
            "pytest-aioresponses==0.2.0",
            "pytest-alembic==0.10.7",
            "pytest-sqlalchemy==0.4.0",
            "pytest-postgresql==5.0.0",
            "pytest-redis==3.0.2",
            "pytest-black==0.3.12",
            "pytest-mypy==0.10.3",
            "pytest-ruff==0.2.1",
            "pytest-deadfixtures==2.2.1",
            "pytest-recording==0.13.1",
            "pytest-responses==0.5.1",
            "pytest-socket==0.6.0",
            "pytest-subtests==0.11.0",
            "pytest-testmon==2.1.1",
            "pytest-vcr==1.0.2",
            "pytest-variables==3.0.0",
            "pytest-watch==4.2.0",
        ],
        "docs": [
            "sphinx>=7.2.0",
            "sphinx-rtd-theme>=2.0.0",
            "sphinx-autodoc-typehints>=1.25.0",
            "sphinx-click>=5.1.0",
            "myst-parser>=2.0.0",
            "nbsphinx>=0.9.0",
            "sphinx-copybutton>=0.5.0",
            "sphinx-design>=0.5.0",
            "sphinx-inline-tabs>=2023.4.21",
            "sphinx-notfound-page>=1.0.0",
            "sphinx-prompt>=1.8.0",
            "sphinx-tabs>=3.4.0",
            "sphinx-togglebutton>=0.3.0",
            "sphinxcontrib-mermaid>=0.9.0",
            "sphinxcontrib-plantuml>=0.27",
            "sphinxcontrib-programoutput>=0.17",
            "sphinxcontrib-spelling>=8.0.0",
            "sphinxext-opengraph>=0.9.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "dspy-meme-gen=dspy_meme_gen.cli:main",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Multimedia :: Graphics",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Framework :: AsyncIO",
        "Framework :: FastAPI",
        "Framework :: Pytest",
        "Framework :: SQLAlchemy",
        "Typing :: Typed",
    ],
    project_urls={
        "Bug Reports": "https://github.com/yourusername/dspy-meme-gen/issues",
        "Source": "https://github.com/yourusername/dspy-meme-gen",
        "Documentation": "https://dspy-meme-gen.readthedocs.io/",
    },
    include_package_data=True,
    zip_safe=False,
)
