blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/jmanhype/MemesPy/discussions
    about: Ask questions and discuss ideas
  - name: 📚 Documentation
    url: https://github.com/jmanhype/MemesPy/wiki
    about: Check out the documentation